### ISSUE TITLE
SO_Tree: Add SVG support for sequenceontology.org/miso

### ISSUE THREAD

**Issue by Artoria2e5** [The-Sequence-Ontology/SOBA#1]
The current pictures on SO.org are basically unreadable. Here is a fresh example (from http://www.sequenceontology.org/miso/current_release/term/SO:0000375):

![image](https://user-images.githubusercontent.com/6459309/101502807-5baaa400-39ac-11eb-8bba-e329f0dc7806.png)

Instead of doing the old higher-res image thing, we could make this image even better by just taking the SVG vector output from GraphViz. The SVG format is widely supported on the web, and it tends to produce much smaller images.

(I don't know who to talk to for actually switching the web miso thing to SVG after soba has it though.)

**Comment by Artoria2e5** [comment]
Okay, so it's GD not (or *and*?) GraphViz. Apparently there's a special GD::SVG module for SVG, since plain GD is bitmap only.

**Comment by srynobio** [comment]
If you simply click on the image it will allow you to view it in higher/better resolution.  You can also open the image in a new tab to view the image independent, and also in better resolution.

**Comment by Artoria2e5** [comment]
Right, but we can get rid of ALL the different resolution magic with SVG. Even the bigger image looks bad with the thin, times text and the zaggy lines. SVG rendered on the browser would not look like that.

![image](https://user-images.githubusercontent.com/6459309/101503794-7598b680-39ad-11eb-8be7-4c68c1da872f.png)
